/**
 * Authentication Service
 * Handles Telegram authentication via NestJS backend
 */

import { supabase } from '../lib/supabaseClient';

const BACKEND_URL = import.meta.env.VITE_BACKEND_URL || 'https://asrtalink.vip';

export interface AuthResponse {
  accessToken: string;
  user: {
    id: string;
    telegram_id: number;
    username: string | null;
    first_name: string | null;
    last_name: string | null;
    avatar_url: string | null;
  };
}

export class AuthService {
  private static accessToken: string | null = null;

  /**
   * Authenticates user with Telegram initData
   */
  static async authenticateWithTelegram(initData: string): Promise<AuthResponse> {
    console.log('[AuthService] Starting authentication...');
    console.log('[AuthService] Backend URL:', BACKEND_URL);

    try {
      console.log('[AuthService] Sending request to:', `${BACKEND_URL}/api/auth/telegram`);

      const response = await fetch(`${BACKEND_URL}/api/auth/telegram`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({ initData }),
      });

      console.log('[AuthService] Response status:', response.status);

      if (!response.ok) {
        const errorText = await response.text();
        console.error('[AuthService] Error response:', errorText);
        let error;
        try {
          error = JSON.parse(errorText);
        } catch {
          error = { message: errorText };
        }
        throw new Error(error.message || 'Authentication failed');
      }

      const result = await response.json();
      console.log('[AuthService] Response data:', { success: result.success, hasData: !!result.data });

      if (!result.success || !result.data) {
        throw new Error('Invalid authentication response');
      }

      const { accessToken, user } = result.data;
      console.log('[AuthService] User authenticated:', { userId: user.id, telegramId: user.telegram_id });

      // Store token
      this.accessToken = accessToken;
      localStorage.setItem('access_token', accessToken);
      console.log('[AuthService] Token stored in localStorage');

      // Set token for Supabase client (for RLS)
      // Note: This works even without Supabase Auth enabled
      // The JWT token generated by backend is compatible with Supabase RLS
      try {
        await supabase.auth.setSession({
          access_token: accessToken,
          refresh_token: accessToken,
        });
        console.log('[AuthService] Supabase session set successfully');
      } catch (sessionError) {
        // If Supabase Auth is not enabled (no auth schema), this might fail
        // But RLS will still work with the JWT token in the format { sub, role, aud }
        console.warn('[AuthService] Could not set Supabase session (auth may not be enabled):', sessionError);
        console.log('[AuthService] RLS will still work via JWT token');
      }

      console.log('[AuthService] ✅ Authentication completed successfully');
      return { accessToken, user };
    } catch (error) {
      console.error('[AuthService] ❌ Authentication failed:', error);
      throw error;
    }
  }

  /**
   * Gets stored access token
   */
  static getAccessToken(): string | null {
    if (!this.accessToken) {
      this.accessToken = localStorage.getItem('access_token');
    }
    return this.accessToken;
  }

  /**
   * Clears authentication
   */
  static async logout(): Promise<void> {
    this.accessToken = null;
    localStorage.removeItem('access_token');
    await supabase.auth.signOut();
  }

  /**
   * Checks if user is authenticated
   */
  static isAuthenticated(): boolean {
    return !!this.getAccessToken();
  }

  /**
   * Gets authorization header for API requests
   */
  static getAuthHeader(): Record<string, string> {
    const token = this.getAccessToken();
    if (!token) {
      return {};
    }
    return {
      Authorization: `Bearer ${token}`,
    };
  }
}

export default AuthService;
